services:
  pgnn:
    build:
      context: .
      dockerfile: Dockerfile
    image: pgnn:latest
    environment:
      - OUTPUT_ROOT=/app/results
    volumes:
      - ./data:/app/data
      - ./results:/app/results

    command: ["python3", "main.py"]

    stdin_open: true
    tty: true
